services:
  sing-box:
    image: ghcr.io/minlaxz/nekohasekai:neko
    pull_policy: always
    restart: unless-stopped
    command: ["/sing-box/sing-box", "run", "-C", "/sing-box/configs"]
    mem_limit: 128m
    mem_reservation: 64m
    memswap_limit: -1 # no swap limit
    networks:
      - nekohasekai-net
    ports:
      - "${START_PORT}-${END_PORT}:${START_PORT}-${END_PORT}/tcp"
      - "${START_PORT}-${END_PORT}:${START_PORT}-${END_PORT}/udp"
    volumes:
      - ./cache:/sing-box/cache
      - ./configs:/sing-box/configs:ro
      - ./certs:/sing-box/certs:ro
      - ./public:/sing-box/public:ro
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:15
    restart: unless-stopped
    mem_limit: 128m
    mem_reservation: 64m
    memswap_limit: -1 # no swap limit
    networks:
      wg:
        ipv4_address: 10.42.42.42
        ipv6_address: fdcc:ad94:bacf:61a3::2a
      caddy-net:
    expose:
      - "51821"
    ports:
      - "${WG_PORT}:51820/udp" # need to open UDP 8888 on your firewall
    volumes:
      - ./wg-data:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1
    environment:
      - PORT=51821
      - HOST=0.0.0.0
      - INSECURE=false
    labels:
      caddy: ${WG_HOST}
      caddy.reverse_proxy: "{{upstreams 51821}}"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    profiles:
      - full

  headscale:
    image: docker.io/headscale/headscale:0.27.1
    restart: unless-stopped
    command: serve
    mem_limit: 128m
    mem_reservation: 64m
    memswap_limit: -1 # no swap limit
    networks:
      - caddy-net
    expose:
      - "8080"
    volumes:
      - ./hs-data/config:/etc/headscale
      - ./hs-data/lib:/var/lib/headscale
      - ./hs-data/run:/var/run/headscale
    healthcheck:
      test: ["CMD", "headscale", "version"]
    labels:
      caddy: ${HS_HOST}
      caddy.reverse_proxy: "{{upstreams 8080}}"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    profiles:
      - full

networks:
  nekohasekai-net:
    driver: bridge
  caddy-net:
    external: true
  wg:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 10.42.42.0/24
        - subnet: fdcc:ad94:bacf:61a3::/64
