services:
  headscale:
    image: docker.io/headscale/headscale:0.27.1
    restart: unless-stopped
    command: serve
    mem_limit: 128m
    mem_reservation: 64m
    memswap_limit: -1 # no swap limit
    networks:
      - caddy-net
    expose:
      - "8080"
    volumes:
      - ./hs-config:/etc/headscale
      - ./hs-lib:/var/lib/headscale
      - ./hs-run:/var/run/headscale
    healthcheck:
      test: ["CMD", "headscale", "version"]
    labels:
      caddy: ${HS_HOST}
      caddy.reverse_proxy: "{{upstreams 8080}}"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  caddy-net:
    external: true
