name: "Build and push singbox image"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "nekohasekai/generator.py"
      - "nekohasekai/init.sh"
      - "api/app/*.py"
      - "api/templates/*.html"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  Build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-qemu-action@v3.0.0
      - uses: docker/setup-buildx-action@v3.0.0

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ghcr doesn't support ipv6 yet.
      - uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64, linux/arm64
          context: ./nekohasekai
          file: ./nekohasekai/Dockerfile
          tags: |
            ${{ env.IMAGE_NAME }}:nekohasekai
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:nekohasekai

      - uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64, linux/arm64
          context: ./api
          file: ./api/Dockerfile
          tags: |
            ${{ env.IMAGE_NAME }}:nekohasekai-api
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:nekohasekai-api
